### ISSUE TITLE
ImportError: cannot import name 'DB' from 'pya2l'

### ISSUE THREAD

**Issue by angervision** [bri3d/a2l2xdf#9]
Traceback (most recent call last):
  File "d:\Data\a2l2xdf-master\a2l2xdf.py", line 6, in <module>
    from pya2l import DB, model
ImportError: cannot import name 'DB' from 'pya2l' (C:\Users\An\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pya2l\__init__.py)

**Comment by bri3d** [comment]
`pip install pya2l` ?

**Comment by angervision** [comment]
Yeah, done that as a prerequisite step. No luck.

**Comment by LarochelleJ** [comment]
`pip install pya2ldb`
